spring:
  datasource:
    url: jdbc:h2:mem:yourDB
  data:
    rest:
      base-path: /api

taco:
  orders:
  pageSize: 10

logging:
  level:
  tacos: DEBUG



---
profiles: prod

datasource:
  url: jdbc:mysql://localhost/tacocloud
  username: tacouser
  password: tacopassword

logging:
  level:
    tacos: WARN